name: Notebook CI

on:
  push:
  pull_request:

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    timeout-minutes: 3

    steps:
      - name: Checkout repository
        uses : action/checkout@v3

      - name : Set up python
        uses: sction/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: 
            python -m pip install --upgrade pip
            pip install papermill jupyter
            pip install -r requiremnts.txt

      - name: Run CustomerSegmentation.ipynb (max 180s)
        run: 
            timeout 180s papermill CustomerSegmentation.ipynb output.ipynb
